export const generalQuestions = [
  {
    id: 1,
    question: "How many countries has Nepal allowed the labour permit?",
    answer: "111",
    nepaliQuestion: "नेपालले कति देशमा श्रम स्वीकृति दिएको छ ?",
    nepaliAnswer: "111",
  },
  {
    id: 2,
    question: "During which period was Kathmandu divided into three kingdoms?",
    answer: "Malla Period",
    nepaliQuestion: "कुन अवधिमा काठमाडौंलाई तीन राज्यमा विभाजन गरिएको थियो?",
    nepaliAnswer: "मल्ल काल",
  },
  {
    id: 3,
    question: "Which metal is liquid at room temperature?",
    answer: "Mercury",
    nepaliQuestion: "कोठाको तापक्रममा कुन धातु तरल हुन्छ?",
    nepaliAnswer: "Mercury",
  },
  {
    id: 4,
    question: "When is the Earth Day celebrated?",
    answer: "April 22",
    nepaliQuestion: "पृथ्वी दिवस कहिले मनाइन्छ?",
    nepaliAnswer: "२२ अप्रिल",
  },
  {
    id: 5,
    question: "Who is the current IGP of Nepal?",
    answer: "IGP Dipak Thapa",
    nepaliQuestion: "नेपालको वर्तमान IGP को हुनुहुन्छ?",
    nepaliAnswer: "आई.जी.पी. दिपक थापा",
  },
  {
    id: 6,
    question: "What is the anti-corruption body in Nepal?",
    answer: "Commission for Investigation of Abuse of Authority (CIAA)",
    nepaliQuestion: "नेपालमा भ्रष्टाचार विरोधी निकाय कुन हो ?",
    nepaliAnswer: "अख्तियार दुरुपयोग अनुसन्धान आयोग",
  },
  {
    id: 7,
    question: "Which year did Nepal become untouchable‑free nation?",
    answer: "2073 BS",
    nepaliQuestion: "नेपाल छुवाछुत मुक्त राष्ट्र कुन साल भयो ?",
    nepaliAnswer: "बि. स.२०७३",
  },
  {
    id: 8,
    question: "What percentage of the total population of Nepal has the access to electricity?",
    answer: "99%",
    nepaliQuestion: "नेपालको कुल जनसंख्याको कति प्रतिशतले बिजुलीको पहुँचमा छन्?",
    nepaliAnswer: "९९%",
  },
  {
    id: 9,
    question: "What is the total budget of Nepal for the Year 2082/083?",
    answer: "19 Kharabs 64 Arabs 11 Crores",
    nepaliQuestion: "आर्थिक वर्ष २०८२/०८३ को लागि नेपालको कुल बजेट कति छ ?",
    nepaliAnswer: "१९ खरब ६४ अरब ११ करोड",
  },
  {
    id: 10,
    question: "Which large tech company is the world's largest software producer?",
    answer: "Microsoft Corporation",
    nepaliQuestion: "संसारको सबैभन्दा ठूलो सफ्टवेयर उत्पादक कुन ठूलो टेक कम्पनी हो?",
    nepaliAnswer: "माइक्रोसफ्ट कर्पोरेशन",
  },
  {
    id: 11,
    question: "What is the maximum tenure age for Nepali Supreme Court Chief Justice?",
    answer: "65 years",
    nepaliQuestion: "नेपाली सर्वोच्च अदालतका प्रधानन्यायाधीशको अधिकतम कार्यकाल उमेर कति हो?",
    nepaliAnswer: "65 वर्ष",
  },
  {
    id: 12,
    question: "What is the value of Pi (π) up to two decimal places?",
    answer: "3.14",
    nepaliQuestion: "दुई दशमलव स्थान सम्म Pi (π) को मान के हो?",
    nepaliAnswer: "३.१४",
  },
  {
    id: 13,
    question: "Who is the current chairman of Public Service Commission Nepal?",
    answer: "Madhav Prasad Regmi",
    nepaliQuestion: "लोकसेवा आयोग नेपालको वर्तमान अध्यक्ष को हुनुहुन्छ?",
    nepaliAnswer: "माधव प्रसाद रेग्मी",
  },
  {
    id: 14,
    question: "What is Nepal’s current time zone?",
    answer: "GMT +5:45",
    nepaliQuestion: "नेपालको हालको समय क्षेत्र के हो?",
    nepaliAnswer: "GMT +5:45",
  },
  {
    id: 15,
    question: 'Who wrote "Karnali Blues"?',
    answer: "Buddhi Sagar",
    nepaliQuestion: '"कर्णाली ब्लुज" कसले लेखेका थिए ?',
    nepaliAnswer: "बुद्ध सागर",
  },
  {
    id: 16,
    question: "Where is the lowest point of the Asian Highway located?",
    answer: "Singapore",
    nepaliQuestion: "एसियाली राजमार्गको सबैभन्दा तल्लो बिन्दु कहाँ छ?",
    nepaliAnswer: "सिङ्गापुर",
  },
  {
    id: 17,
    question: "Who is the Chief of Nepal Army?",
    answer: "General Ashok Raj Sigdel",
    nepaliQuestion: "नेपाली सेनाका प्रमुख को हुन्?",
    nepaliAnswer: "जनरल अशोकराज सिग्देल",
  },
  {
    id: 18,
    question: "Who is the current governor of Madhesh Pradesh?",
    answer: "Sumitra Subedi Bhandari",
    nepaliQuestion: "मधेश प्रदेशका वर्तमान गभर्नर को हुनुहुन्छ?",
    nepaliAnswer: "सुमित्रा सुवेदी भण्डारी",
  },
  {
    id: 19,
    question: "What is the name of Nepal’s international airport in Lumbini?",
    answer: "Gautam Buddha International Airport",
    nepaliQuestion: "लुम्बिनीमा रहेको नेपालको अन्तर्राष्ट्रिय विमानस्थलको नाम के हो?",
    nepaliAnswer: "गौतम बुद्ध अन्तर्राष्ट्रिय विमानस्थल",
  },
  {
    id: 20,
    question: "How many members are there in the National Assembly in Nepal?",
    answer: "59",
    nepaliQuestion: "नेपालमा राष्ट्रिय सभामा कति सदस्य छन्?",
    nepaliAnswer: "५९",
  },
  {
    id: 21,
    question: "Which district has the most suspension bridges in Nepal?",
    answer: "Baglung",
    nepaliQuestion: "नेपालमा सबैभन्दा बढी झोलुङ्गे पुल भएको जिल्ला कुन हो ?",
    nepaliAnswer: "बागलुङ",
  },
  {
    id: 22,
    question: "Who is known as the Mother Teressa of Nepal?",
    answer: "Anuradha Koirala",
    nepaliQuestion: "नेपालको मदर टेरेसा भनेर कसलाई चिनिन्छ?",
    nepaliAnswer: "अनुराधा कोइराला",
  },
  {
    id: 23,
    question: "What is the currency of Bhutan?",
    answer: "Ngultrum",
    nepaliQuestion: "भुटानको मुद्रा के हो?",
    nepaliAnswer: "Ngultrum",
  },
  {
    id: 24,
    question: "What year was the first iPhone released?",
    answer: "2007",
    nepaliQuestion: "पहिलो आईफोन कुन वर्ष रिलिज भएको थियो?",
    nepaliAnswer: "2007",
  },
  {
    id: 25,
    question: "What does “URL” stand for?",
    answer: "Uniform Resource Locator",
    nepaliQuestion: '"URL" को अर्थ के हो?',
    nepaliAnswer: "समान संसाधन लोकेटर",
  },
  {
    id: 26,
    question: "Which country is both in Asia and Europe?",
    answer: "Turkey",
    nepaliQuestion: "एसिया र युरोप दुबैमा कुन देश छ?",
    nepaliAnswer: "टर्की",
  },
  {
    id: 27,
    question: "Which US state is the largest by area?",
    answer: "Alaska",
    nepaliQuestion: "क्षेत्रफलको आधारमा सबैभन्दा ठूलो अमेरिकी राज्य कुन हो?",
    nepaliAnswer: "अलास्का",
  },
  {
    id: 28,
    question: "Which country was the first to grant women the right to vote?",
    answer: "New Zealand",
    nepaliQuestion: "महिलालाई मतदानको अधिकार दिने पहिलो देश कुन हो?",
    nepaliAnswer: "न्यूजिल्याण्ड",
  },
  {
    id: 29,
    question: "Who was the first emperor of the Roman Empire?",
    answer: "Augustus Caesar",
    nepaliQuestion: "रोमन साम्राज्यका प्रथम सम्राट को थिए?",
    nepaliAnswer: "अगस्टस सिजर",
  },
  {
    id: 30,
    question: "What year did India gain independence from Britain?",
    answer: "1947",
    nepaliQuestion: "भारतले बेलायतबाट कति वर्ष स्वतन्त्रता प्राप्त गर्यो?",
    nepaliAnswer: "१९४७",
  },
  {
    id: 31,
    question: "What is the standard length of a marathon?",
    answer: "42.195 kilometers (26.2 miles)",
    nepaliQuestion: "म्याराथनको मानक लम्बाइ कति हुन्छ?",
    nepaliAnswer: "४२.१९५ किलोमिटर (२६.२ माइल)",
  },
  {
    id: 32,
    question: "When did Nepal launch its first satellite into space?",
    answer: "April 19, 2019",
    nepaliQuestion: "नेपालले आफ्नो पहिलो भूउपग्रह कहिले अन्तरिक्षमा प्रक्षेपण गर्यो?",
    nepaliAnswer: "अप्रिल १९, २०१९",
  },
  {
    id: 33,
    question: "Which literary award is considered the most prestigious in Nepal?",
    answer: "Madan Puraskar",
    nepaliQuestion: "नेपालमा कुन साहित्यिक पुरस्कारलाई सबैभन्दा प्रतिष्ठित मानिन्छ?",
    nepaliAnswer: "मदन पुरस्कार",
  },
  {
    id: 34,
    question: "Who is the first Nepali woman to become a Guinness World Record holder?",
    answer: "Chhurim Sherpa",
    nepaliQuestion: "गिनिज वल्र्ड रेकर्ड होल्डर बन्ने पहिलो नेपाली महिला को हुन्?",
    nepaliAnswer: "छुरीम शेर्पा",
  },
  {
    id: 35,
    question: "Who was the first Nepali musician to perform at the UN?",
    answer: "Ani Choying Drolma",
    nepaliQuestion: "UN मा प्रस्तुति दिने पहिलो नेपाली संगीतकार को थिए?",
    nepaliAnswer: "आनी छोइङ डोल्मा",
  },
  {
    id: 36,
    question: "When did Nepal start exporting electricity to India under energy banking?",
    answer: "Asar 27, 2076 B.S.",
    nepaliQuestion: "नेपालले कहिलेदेखि ऊर्जा सञ्चितीकरण अन्तर्गत भारतमा बिजुली निर्यात गर्न थाल्यो?",
    nepaliAnswer: "बि.स.२०७६ असार २७",
  },
  {
    id: 37,
    question: "When did Nepal promulgate secularism officially?",
    answer: "Jeth 4, 2063 B.S.",
    nepaliQuestion: "नेपालले धर्मनिरपेक्षताको औपचारिक घोषणा कहिले गर्यो?",
    nepaliAnswer: "बि.स.२०६३ जेठ ४",
  },
  {
    id: 38,
    question: "What academic medal is awarded by the President on Education Day?",
    answer: "Nepal Bidya Bhusan Padak",
    nepaliQuestion: "नेपालमा शिक्षा दिवसमा राष्ट्रपतिद्वारा कुन शैक्षिक पदक प्रदान गरिन्छ?",
    nepaliAnswer: "नेपाल विद्या भूषण पदक",
  },
  {
    id: 39,
    question: "What does ANFA stand for?",
    answer: "All Nepal Football Association",
    nepaliQuestion: "ANFA को पूरा रुप के हो?",
    nepaliAnswer: "All Nepal Football Association",
  },
  {
    id: 40,
    question: "What is the full form of NASA?",
    answer: "National Aeronautics and Space Administration",
    nepaliQuestion: "NASA को पूरा रुप के हो?",
    nepaliAnswer: "National Aeronautics and Space Administration",
  },
]

export const rapidFireSets = {
  "Set-A": [
    { id: 1, question: "Who is the captain of Nepal’s National Team?", answer: "Rohit Poudel" },
    { id: 2, question: "What is the formula for the area of a circle?", answer: "πr²" },
    { id: 3, question: "Who is known as the “King of Pop”?", answer: "Michael Jackson" },
    { id: 4, question: "Which is the longest river in Nepal?", answer: "Karnali" },
    { id: 5, question: "What is the currency of the United Kingdom?", answer: "Pound Sterling" },
    { id: 6, question: "What color is an octopus’s blood?", answer: "Blue" },
    { id: 7, question: "What is the process of converting solid to gas directly?", answer: "Sublimation" },
    { id: 8, question: "Who is the founder of Meta?", answer: "Mark Zuckerberg" },
    { id: 9, question: "Which organ purifies blood in the human body?", answer: "Kidney" },
    { id: 10, question: "What is the sum of the first 10 natural numbers?", answer: "55" },
  ],
  "Set-B": [
    { id: 1, question: "What is the sum of interior angles of a triangle?", answer: "180°" },
    { id: 2, question: "What is the capital of Egypt?", answer: "Cairo" },
    { id: 3, question: "Who invented television?", answer: "John Logie Baird" },
    { id: 4, question: "In which year did World War II end?", answer: "1945" },
    { id: 5, question: "Which vitamin is produced in the body with sunlight?", answer: "Vitamin D" },
    { id: 6, question: "Which color is associated with Goddess Saraswati?", answer: "White" },
    { id: 7, question: "Which is the largest gland in the human body?", answer: "Liver" },
    { id: 8, question: "Who discovered America?", answer: "Christopher Columbus" },
    { id: 9, question: "Which gas is most abundant in Earth’s atmosphere?", answer: "Nitrogen" },
    { id: 10, question: "What planet is known as the Red Planet?", answer: "Mars" },
  ],
  "Set-C": [
    { id: 1, question: "Which continent has the most countries?", answer: "Africa" },
    { id: 2, question: "What is the square root of 144?", answer: "12" },
    { id: 3, question: "What is the smallest continent?", answer: "Australia" },
    { id: 4, question: "When is Constitution Day celebrated in Nepal?", answer: "Asoj 3" },
    { id: 5, question: "What is the unit of electric current?", answer: "Ampere" },
    { id: 6, question: "Who invented dynamo?", answer: "Micheal Faraday" },
    { id: 7, question: "What is 25% of 200?", answer: "50" },
    { id: 8, question: "What is the atomic number of oxygen?", answer: "8" },
    { id: 9, question: "What is the capital of Australia?", answer: "Canberra" },
    { id: 10, question: "Who is known as the father of mathematics?", answer: "Archimedes" },
  ],
  "Set-D": [
    { id: 1, question: "What does ATM stand for?", answer: "Automated Teller Machine" },
    { id: 2, question: "Who is known as the internet man of Nepal?", answer: "Mahabir Pun" },
    { id: 3, question: "Who introduced English education in Nepal?", answer: "Jung Bahadur Rana" },
    { id: 4, question: "Who is called Natya Siromani (Shakespeare of Nepal)?", answer: "Balkrishna Sama" },
    { id: 5, question: "Who invented reusable rockets?", answer: "Elon Musk" },
    { id: 6, question: "Which language is the second most spoken after Nepali in Nepal?", answer: "Maithili" },
    { id: 7, question: "Who was the first President of the United States?", answer: "George Washington" },
    { id: 8, question: "What is the highest-grossing film of all time?", answer: "“Avatar”" },
    { id: 9, question: "Who has won the most Olympic gold medals?", answer: "Michael Phelps" },
    { id: 10, question: "Who is the current president of Russia?", answer: "Vladimir Putin" },
  ],
}

export const buzzerQuestions = [
  {
    id: 1,
    question: "Which sport is Sangina Baidhya related to?",
    answer: "Taekwondo",
    nepaliQuestion: "संगिना वैद्य कुन खेलसँग सम्बन्धित छ?",
    nepaliAnswer: "तेक्वान्दो",
  },
  {
    id: 2,
    question: "Who is the current Education, Science and Technology Minister of Nepal?",
    answer: "Raghuji Panta",
    nepaliQuestion: "नेपालको वर्तमान शिक्षा, विज्ञान तथा प्रविधि मन्त्री को हुनुहुन्छ?",
    nepaliAnswer: "रघुजी पन्त",
  },
  {
    id: 3,
    question: "What does “HTTP” stand for?",
    answer: "HyperText Transfer Protocol",
    nepaliQuestion: '"HTTP" को पूरा रुप के हो?',
    nepaliAnswer: "HyperText Transfer Protocol",
  },
  {
    id: 4,
    question: "What is the perimeter of a square with side 6 cm?",
    answer: "24 cm",
    nepaliQuestion: "सेमी पक्ष भएको वर्गको परिधि कति हुन्छ?",
    nepaliAnswer: "24 सेमी",
  },
  {
    id: 5,
    question: "What is the total population of Nepal according to the Cencus 2078?",
    answer: "2,91,64,578",
    nepaliQuestion: "जनगणना २०७८ अनुसार नेपालको कुल जनसंख्या कति छ?",
    nepaliAnswer: "२,९१,६४,५७८",
  },
  {
    id: 6,
    question: "What does BIMSTEC stand for?",
    answer: "Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation.",
    nepaliQuestion: "बिमस्टेकको पूरा रुप के हो ?",
    nepaliAnswer: "Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation.",
  },
  {
    id: 7,
    question: "Which district became Nepal’s first Wi-Fi–free district?",
    answer: "Myagdi",
    nepaliQuestion: "नेपालको पहिलो Wi-Fi–free जिल्ला कुन जिल्ला बन्यो?",
    nepaliAnswer: "म्याग्दी",
  },
  {
    id: 8,
    question: "Who is the youngest Nobel Prize winner ever?",
    answer: "Malala Yousafzai",
    nepaliQuestion: "सबैभन्दा कान्छो नोबेल पुरस्कार विजेता को हुन्?",
    nepaliAnswer: "मलाला युसुफजाई",
  },
  {
    id: 9,
    question: "Which country has the most natural lakes?",
    answer: "Canada",
    nepaliQuestion: "सबैभन्दा प्राकृतिक ताल भएको देश कुन हो?",
    nepaliAnswer: "क्यानाडा",
  },
  {
    id: 10,
    question: "Who is the fastest man in the world?",
    answer: "Usain Bolt",
    nepaliQuestion: "संसारको सबैभन्दा छिटो / तीव्र मानिस को हो?",
    nepaliAnswer: "उसैन बोल्ट",
  },
  { id: 11, question: "What is ⅔ of 90?", answer: "60", nepaliQuestion: "90 को ⅔ कतिइ हुन्छ?", nepaliAnswer: "६०" },
  {
    id: 12,
    question: "When was the United Nations formed?",
    answer: "1945",
    nepaliQuestion: "संयुक्त राष्ट्र संघको स्थापना कहिले भयो?",
    nepaliAnswer: "१९४५",
  },
  {
    id: 13,
    question: "How many members are there in the House of Assembly in Nepal?",
    answer: "275",
    nepaliQuestion: "नेपालमा हाल कति पतिनीधि सभा सदस्य रहने व्यवस्था रहेको छ ?",
    nepaliAnswer: "२७५",
  },
  {
    id: 14,
    question: "When is the National Children’s Day celebrated in Nepal?",
    answer: "Bhadra 29",
    nepaliQuestion: "नेपालमा राष्ट्रिय बाल दिवस कहिले मनाइन्छ?",
    nepaliAnswer: "भाद्र २९",
  },
  {
    id: 15,
    question: "What is the boiling point of water?",
    answer: "100°C or 212°F",
    nepaliQuestion: "पानीको उम्लने बिन्दु कति हो?",
    nepaliAnswer: "100°C वा 212°F",
  },
  {
    id: 16,
    question: "Which treaty ended World War I?",
    answer: "Treaty of Versailles",
    nepaliQuestion: "कुन सन्धिले प्रथम विश्वयुद्ध समाप्त गर्यो?",
    nepaliAnswer: "भर्साइलिजको सन्धि",
  },
  {
    id: 17,
    question: "What does NATO stand for?",
    answer: "North Atlantic Treaty Organization",
    nepaliQuestion: "NATO को पूरा रुप के हो ?",
    nepaliAnswer: "North Atlantic Treaty Organization",
  },
  {
    id: 18,
    question: "What ancient civilization built the pyramids?",
    answer: "Egyptians",
    nepaliQuestion: "कुन पुरातन सभ्यताले पिरामिडहरू बनायो?",
    nepaliAnswer: "इजिप्टियन",
  },
  {
    id: 19,
    question: "What is the largest 2-digit prime number?",
    answer: "97",
    nepaliQuestion: "सबैभन्दा ठूलो २ अंकको अभाज्य संख्या के हो?",
    nepaliAnswer: "९७",
  },
  {
    id: 20,
    question: "What is the full form of NASA?",
    answer: "National Aeronautics and Space Administration",
    nepaliQuestion: "NASA को पूरा रुप के हो?",
    nepaliAnswer: "National Aeronautics and Space Administration",
  },
  {
    id: 21,
    question: "What sport is associated with Wimbledon?",
    answer: "Tennis",
    nepaliQuestion: "विम्बल्डन कुन खेलसँग सम्बन्धित छ?",
    nepaliAnswer: "टेनिस",
  },
  {
    id: 22,
    question: "Which hydropower was Nepal’s first?",
    answer: "Phewa (Pherping) Hydropower",
    nepaliQuestion: "नेपालको पहिलो जलविद्युत आयोजना कुन हो?",
    nepaliAnswer: "फेवा (फेरपिङ) जलविद्युत आयोजना",
  },
  {
    id: 23,
    question: "What is the first satellite to go to the space?",
    answer: "Sputnik-I",
    nepaliQuestion: "अन्तरिक्षमा जाने पहिलो उपग्रह कुन हो?",
    nepaliAnswer: "स्पुतनिक-I",
  },
  {
    id: 24,
    question: "What is the oldest civilization in the world?",
    answer: "Mesopotamian",
    nepaliQuestion: "संसारको सबैभन्दा पुरानो सभ्यता के हो?",
    nepaliAnswer: "मेसोपोटामिया",
  },
  {
    id: 25,
    question: "In which country did the Olympic Games originate?",
    answer: "Greece",
    nepaliQuestion: "ओलम्पिक खेलकुदको सुरुवात कुन देशमा भएको थियो?",
    nepaliAnswer: "ग्रीस",
  },
  {
    id: 26,
    question: "What is the imaginary line that divides the Earth into northern and southern hemisphere?",
    answer: "Equator",
    nepaliQuestion: "पृथ्वीलाई उत्तरी र दक्षणी गोलार्धमा विभाजन गर्ने काल्पनिक रेखा के हो?",
    nepaliAnswer: "भूमध्य रेखा",
  },
  {
    id: 27,
    question: "Which international body is responsible for maintaining peace worldwide?",
    answer: "United Nations Organization",
    nepaliQuestion: "कुन अन्तर्राष्ट्रिय निकाय विश्वभर शान्ति कायम राख्न जिम्मेवार छ?",
    nepaliAnswer: "संयुक्त राष्ट्र संघ",
  },
  {
    id: 28,
    question: "Who is the current Chief Minister of Madhesh Pradesh?",
    answer: "Satish Kumar Singh",
    nepaliQuestion: "मधेस प्रदेशका वर्तमान मुख्यमन्त्री को हुनुहुन्छ?",
    nepaliAnswer: "सतिस कुमार सिँह",
  },
  {
    id: 29,
    question: "Which international body is responsible for maintaining peace worldwide?",
    answer: "United Nations Organization",
    nepaliQuestion: "कुन अन्तर्राष्ट्रिय निकाय विश्वभर शान्ति कायम राख्न जिम्मेवार छ?",
    nepaliAnswer: "संयुक्त राष्ट्र संघ",
  },
  {
    id: 30,
    question: "Who is the current Chief Minister of Madhesh Pradesh?",
    answer: "Satish Kumar Singh",
    nepaliQuestion: "मधेस प्रदेशका वर्तमान मुख्यमन्त्री को हुनुहुन्छ?",
    nepaliAnswer: "सतिस कुमार सिँह",
  },
]
